### ISSUE TITLE
Effect of finetuning CNN backbones

### ISSUE THREAD

**Issue by jayleicn** [woodfrog/vse_infty#2]
Hi Jiacheng @woodfrog and Hexiang @hexiang-hu,

Nice work on image-text retrieval! I am really amazed by the performance obtained by this simple model and am trying to dissect what factors lead to this success.

I noticed from the paper that the CNN backbone is finetuned along with the whole model when using grid features, but did not find anywhere in the paper that discusses the effect of such end-to-end fine-tuning. Could you provide some details on the performance gain obtained with this strategy?

Best,
Jie

**Comment by woodfrog** [comment]
Hi Jie,

Thanks for your interest in our work!  

When using grid features (i.e., the direct feature maps from a standard CNN), the default setting is to finetune the backbone along with the whole model. For example, in [VSE++](https://arxiv.org/abs/1707.05612), although results of not fine-tuning the backbone are also reported, the best results are obtained by fine-tuning the CNN.  Other related works using grid features also fine-tune the CNN backbone, like [this](https://arxiv.org/abs/1712.02036) and [this](https://arxiv.org/abs/1711.06420), etc.

In our implementations for using grid features, the only difference to VSE++ is that we increase the image resolution to 512x512, which is suggested by [this paper](https://arxiv.org/abs/2001.03615) as we mentioned in our paper. The "Our: VSE++"  entry in the main tables is the VSE++ model with increased image resolution.   As for the performance gap between fine-tuning and not fine-tuning the CNN backbone, I believe it should be similar to those reported in the VSE++ paper. 

Regards,
Jiacheng

**Comment by jayleicn** [comment]
Thank you Jiacheng, this is very helpful! 

A follow-up question: how much performance gain does higher image resolution give? 

Another question: In Table 2, the last row (highlighted), is the only difference between _Our: VSE++_ and _Our: VSE∞_ the pooling function? i.e.,  Average Pool vs. the proposed GPO? 

![image](https://user-images.githubusercontent.com/15768405/115767518-3fb20880-a377-11eb-8dcd-eb746e07a46a.png)


Best,
Jie

**Comment by woodfrog** [comment]
> Thank you Jiacheng, this is very helpful!
> 
> A follow-up question: how much performance gain does higher image resolution give?
> 
> Another question: In Table 2, the last row (highlighted), is the only difference between _Our: VSE++_ and _Our: VSE∞_ the pooling function? i.e., Average Pool vs. the proposed GPO?
> 
> ![image](https://user-images.githubusercontent.com/15768405/115767518-3fb20880-a377-11eb-8dcd-eb746e07a46a.png)
> 
> Best,
> Jie

Question1: I roughly remember that the performance gap between 512x512 and 256x256 is something around 5% (absolute improvement) in terms of I2T and T2I's R@1.  We didn't include the exact comparison, but maybe you can refer to the big table (table.9 in the Arxiv version) in our appendix for more details --  "Our: VSE++" with BUTD region feature and BiGRU is better than the original VSE++ entry (ie, the 2nd row), and using "BUTD grid with high resolution" would be slightly better than using "BUTD region" as shown by "VSE \infty" entries. 

Question2: Yes, the differences are all the components described in Sec.3 of our paper, including the pooling operator and the augmentation on feature size.

**Comment by jayleicn** [comment]
Thanks Jiacheng! This makes sense!
