### ISSUE TITLE
Question about dataloader and lengths input

### ISSUE THREAD

**Issue by Cloveryww** [woodfrog/vse_infty#4]
Hi,
I have a question about your dataloader for GPO's input "lengths". In fact, the TextEncoder's GPO module need captions' lengths but the dataloader return the "index"??
Is any problems in your code or i make a misunderstood？
https://github.com/woodfrog/vse_infty/blob/c9943b2327a568bb9d1a628bc53f74f21eb97c75/lib/datasets/image_caption.py#L95
https://github.com/woodfrog/vse_infty/blob/c9943b2327a568bb9d1a628bc53f74f21eb97c75/lib/encoders.py#L175

**Comment by woodfrog** [comment]
Hi, 

The length of the caption is generated for each batch in the collate function here: https://github.com/woodfrog/vse_infty/blob/c9943b2327a568bb9d1a628bc53f74f21eb97c75/lib/datasets/image_caption.py#L277

**Comment by Cloveryww** [comment]
Oh! I see. Thanks!!!
