### ISSUE TITLE
Where can I find train_ids.txt, testall_caps.txt .. etc?

### ISSUE THREAD

**Issue by pseulki** [woodfrog/vse_infty#7]
Hello, 
Thank you for sharing your nice work!

I wonder where I can find the text files in /data/coco/precomp/., such as train_ids.txt, train_caps.txt, testall_caps.txt .. and so on.
I would really appreciate your help!
Thanks!!

**Comment by woodfrog** [comment]
Thank you for your interest! 

As described in the readme, these data files can be downloaded from [the repo of SCAN](https://github.com/kuanghuei/SCAN#download-data). They provide the following commands:

```
wget https://iudata.blob.core.windows.net/scan/data.zip
wget https://iudata.blob.core.windows.net/scan/vocab.zip
```

**Comment by pseulki** [comment]
Thank you! :)
