### ISSUE TITLE
about the dataset download

### ISSUE THREAD

**Issue by Ray-Zhen** [woodfrog/vse_infty#8]
Hello
Thanks for your nice work, the data files from the repo of SCAN cannot download data now, can you provide the download link again?

**Comment by woodfrog** [comment]
Hi, which files are missing? Did you mean the "data.zip" and "vocab.zip" provided by the SCAN repo? I will need to check my backup to see if these files are still there.

**Comment by woodfrog** [comment]
Hi, I checked the repo of SCAN, and many recent issues mentioned that the link to the pre-computed features doesn't work anymore, so I guess you are asking for the same thing. 

I just found out SCAN's pre-computed features from my backup and uploaded a copy [here](https://drive.google.com/file/d/1iY6S-w-vG-4T_v9OvlFkZ1GDPzX5YVtl/view?usp=sharing). I will also update the README to add this link.
