### ISSUE TITLE
Data download failed

### ISSUE THREAD

**Issue by Lxier** [woodfrog/vse_infty#9]
Hello, the data package is too large. I haven't downloaded it successfully for several days. Would you please help me send email 294197320@qq.com? Thanks!

**Comment by woodfrog** [comment]
Hi, there seem to be some issues with Google Drive for downloading large files. I just updated the README and included a new Dropbox link. Can you try the new one?

**Comment by Lxier** [comment]
Yes!!Thanks!!!
